name: iKat
description: ""
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter_spinkit: ^5.2.1
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.20.1
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  url_launcher: ^6.1.10 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ico_res/icon/android/9hdpi.png"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets\images\home\standart\android\home.png
    - assets/images/search/standart/android/search.png
    - assets/images/heart/standart/android/heart.png
    - assets/images/bell/standart/android/bell.png  
    - assets\images\home\touch\android\home.png
    - assets/images/search/touch/android/search.png
    - assets/images/heart/touch/android/heart.png
    - assets/images/bell/touch/android/bell.png  

  fonts:
    - family: Roboto
